
EDIT_TEXT_FOCUS_BG = "#fff"

EDIT_CODE_FOCUS_BG = "#e3eaee"

EDIT_CODE_BG = "#d3daea"

PAGE_BG = "#ffe"

ITEM_BORDER_COLOR = "#bbe"

PAGE_ITEM_MENU_BG = "#eef"

IMAGE_ITEM_TOOLBAR_BG = "rgba(255, 255, 239, 64)"

PAGE_ITEM_MENU_SELECTED = "#eee"

DEFAULT_ITEM_TEXT_COLOR = "#000"

TAB_PANE_BORDER_COLOR = "gray"
